FROM python:3.6-slim

ENV REDIS_HOST ''
ENV REDIS_PORT ''
ENV REDIS_DB ''
ENV REDIS_PASSWORD ''

ENV APP_PORT ''
ENV APP_HOST ''
ENV APP_SECRET ''
ENV APP_DEBUG ''
ENV APP_LOGOUT ''
ENV APP_HOMEPAGE ''

ENV URL_DISCORD ''